<?php

namespace App\Services;

class StateService
{
    /**
     * Get all US states with their abbreviations
     */
    public function getStates(): array
    {
        return [
            'AL' => 'Alabama',
            'AK' => 'Alaska',
            'AZ' => 'Arizona',
            'AR' => 'Arkansas',
            'CA' => 'California',
            'CO' => 'Colorado',
            'CT' => 'Connecticut',
            'DE' => 'Delaware',
            'FL' => 'Florida',
            'GA' => 'Georgia',
            'HI' => 'Hawaii',
            'ID' => 'Idaho',
            'IL' => 'Illinois',
            'IN' => 'Indiana',
            'IA' => 'Iowa',
            'KS' => 'Kansas',
            'KY' => 'Kentucky',
            'LA' => 'Louisiana',
            'ME' => 'Maine',
            'MD' => 'Maryland',
            'MA' => 'Massachusetts',
            'MI' => 'Michigan',
            'MN' => 'Minnesota',
            'MS' => 'Mississippi',
            'MO' => 'Missouri',
            'MT' => 'Montana',
            'NE' => 'Nebraska',
            'NV' => 'Nevada',
            'NH' => 'New Hampshire',
            'NJ' => 'New Jersey',
            'NM' => 'New Mexico',
            'NY' => 'New York',
            'NC' => 'North Carolina',
            'ND' => 'North Dakota',
            'OH' => 'Ohio',
            'OK' => 'Oklahoma',
            'OR' => 'Oregon',
            'PA' => 'Pennsylvania',
            'RI' => 'Rhode Island',
            'SC' => 'South Carolina',
            'SD' => 'South Dakota',
            'TN' => 'Tennessee',
            'TX' => 'Texas',
            'UT' => 'Utah',
            'VT' => 'Vermont',
            'VA' => 'Virginia',
            'WA' => 'Washington',
            'WV' => 'West Virginia',
            'WI' => 'Wisconsin',
            'WY' => 'Wyoming',
            'DC' => 'District of Columbia'
        ];
    }

    /**
     * Get cities for a specific state
     */
    public function getCitiesForState(string $stateCode): array
    {
        $cities = [
            'NY' => [
                'New York' => 'New York',
                'Buffalo' => 'Buffalo',
                'Rochester' => 'Rochester',
                'Yonkers' => 'Yonkers',
                'Syracuse' => 'Syracuse',
                'Albany' => 'Albany',
                'New Rochelle' => 'New Rochelle',
                'Mount Vernon' => 'Mount Vernon',
                'Schenectady' => 'Schenectady',
                'Utica' => 'Utica',
                'White Plains' => 'White Plains',
                'Hempstead' => 'Hempstead',
                'Troy' => 'Troy',
                'Niagara Falls' => 'Niagara Falls',
                'Binghamton' => 'Binghamton'
            ],
            'CA' => [
                'Los Angeles' => 'Los Angeles',
                'San Diego' => 'San Diego',
                'San Jose' => 'San Jose',
                'San Francisco' => 'San Francisco',
                'Fresno' => 'Fresno',
                'Sacramento' => 'Sacramento',
                'Long Beach' => 'Long Beach',
                'Oakland' => 'Oakland',
                'Bakersfield' => 'Bakersfield',
                'Anaheim' => 'Anaheim',
                'Santa Ana' => 'Santa Ana',
                'Riverside' => 'Riverside',
                'Stockton' => 'Stockton',
                'Irvine' => 'Irvine',
                'Fremont' => 'Fremont'
            ],
            'TX' => [
                'Houston' => 'Houston',
                'San Antonio' => 'San Antonio',
                'Dallas' => 'Dallas',
                'Austin' => 'Austin',
                'Fort Worth' => 'Fort Worth',
                'El Paso' => 'El Paso',
                'Arlington' => 'Arlington',
                'Corpus Christi' => 'Corpus Christi',
                'Plano' => 'Plano',
                'Lubbock' => 'Lubbock',
                'Garland' => 'Garland',
                'Irving' => 'Irving',
                'Amarillo' => 'Amarillo',
                'Grand Prairie' => 'Grand Prairie',
                'Brownsville' => 'Brownsville'
            ],
            'FL' => [
                'Jacksonville' => 'Jacksonville',
                'Miami' => 'Miami',
                'Tampa' => 'Tampa',
                'Orlando' => 'Orlando',
                'St. Petersburg' => 'St. Petersburg',
                'Hialeah' => 'Hialeah',
                'Tallahassee' => 'Tallahassee',
                'Fort Lauderdale' => 'Fort Lauderdale',
                'Port St. Lucie' => 'Port St. Lucie',
                'Cape Coral' => 'Cape Coral',
                'Gainesville' => 'Gainesville',
                'Hollywood' => 'Hollywood',
                'Miramar' => 'Miramar',
                'Coral Springs' => 'Coral Springs',
                'Clearwater' => 'Clearwater'
            ],
            'IL' => [
                'Chicago' => 'Chicago',
                'Aurora' => 'Aurora',
                'Rockford' => 'Rockford',
                'Joliet' => 'Joliet',
                'Naperville' => 'Naperville',
                'Springfield' => 'Springfield',
                'Peoria' => 'Peoria',
                'Elgin' => 'Elgin',
                'Waukegan' => 'Waukegan',
                'Champaign' => 'Champaign',
                'Bloomington' => 'Bloomington',
                'Decatur' => 'Decatur',
                'Arlington Heights' => 'Arlington Heights',
                'Evanston' => 'Evanston',
                'Schaumburg' => 'Schaumburg'
            ],
            'PA' => [
                'Philadelphia' => 'Philadelphia',
                'Pittsburgh' => 'Pittsburgh',
                'Allentown' => 'Allentown',
                'Erie' => 'Erie',
                'Reading' => 'Reading',
                'Scranton' => 'Scranton',
                'Bethlehem' => 'Bethlehem',
                'Lancaster' => 'Lancaster',
                'Harrisburg' => 'Harrisburg',
                'Altoona' => 'Altoona',
                'York' => 'York',
                'State College' => 'State College',
                'Wilkes-Barre' => 'Wilkes-Barre',
                'Chester' => 'Chester',
                'Williamsport' => 'Williamsport'
            ],
            'OH' => [
                'Columbus' => 'Columbus',
                'Cleveland' => 'Cleveland',
                'Cincinnati' => 'Cincinnati',
                'Toledo' => 'Toledo',
                'Akron' => 'Akron',
                'Dayton' => 'Dayton',
                'Parma' => 'Parma',
                'Canton' => 'Canton',
                'Youngstown' => 'Youngstown',
                'Lorain' => 'Lorain',
                'Hamilton' => 'Hamilton',
                'Springfield' => 'Springfield',
                'Kettering' => 'Kettering',
                'Elyria' => 'Elyria',
                'Lakewood' => 'Lakewood'
            ],
            'GA' => [
                'Atlanta' => 'Atlanta',
                'Augusta' => 'Augusta',
                'Columbus' => 'Columbus',
                'Macon' => 'Macon',
                'Savannah' => 'Savannah',
                'Athens' => 'Athens',
                'Sandy Springs' => 'Sandy Springs',
                'Roswell' => 'Roswell',
                'Albany' => 'Albany',
                'Johns Creek' => 'Johns Creek',
                'Warner Robins' => 'Warner Robins',
                'Alpharetta' => 'Alpharetta',
                'Marietta' => 'Marietta',
                'Valdosta' => 'Valdosta',
                'Smyrna' => 'Smyrna'
            ],
            'NC' => [
                'Charlotte' => 'Charlotte',
                'Raleigh' => 'Raleigh',
                'Greensboro' => 'Greensboro',
                'Durham' => 'Durham',
                'Winston-Salem' => 'Winston-Salem',
                'Fayetteville' => 'Fayetteville',
                'Cary' => 'Cary',
                'Wilmington' => 'Wilmington',
                'High Point' => 'High Point',
                'Greenville' => 'Greenville',
                'Asheville' => 'Asheville',
                'Concord' => 'Concord',
                'Gastonia' => 'Gastonia',
                'Jacksonville' => 'Jacksonville',
                'Rocky Mount' => 'Rocky Mount'
            ],
            'MI' => [
                'Detroit' => 'Detroit',
                'Grand Rapids' => 'Grand Rapids',
                'Warren' => 'Warren',
                'Sterling Heights' => 'Sterling Heights',
                'Lansing' => 'Lansing',
                'Ann Arbor' => 'Ann Arbor',
                'Flint' => 'Flint',
                'Dearborn' => 'Dearborn',
                'Livonia' => 'Livonia',
                'Westland' => 'Westland',
                'Troy' => 'Troy',
                'Farmington Hills' => 'Farmington Hills',
                'Kalamazoo' => 'Kalamazoo',
                'Wyoming' => 'Wyoming',
                'Rochester Hills' => 'Rochester Hills'
            ],
            'VA' => [
                'Virginia Beach' => 'Virginia Beach',
                'Norfolk' => 'Norfolk',
                'Arlington' => 'Arlington',
                'Richmond' => 'Richmond',
                'Newport News' => 'Newport News',
                'Alexandria' => 'Alexandria',
                'Hampton' => 'Hampton',
                'Roanoke' => 'Roanoke',
                'Portsmouth' => 'Portsmouth',
                'Suffolk' => 'Suffolk',
                'Lynchburg' => 'Lynchburg',
                'Harrisonburg' => 'Harrisonburg',
                'Charlottesville' => 'Charlottesville',
                'Danville' => 'Danville',
                'Blacksburg' => 'Blacksburg'
            ],
            'WA' => [
                'Seattle' => 'Seattle',
                'Spokane' => 'Spokane',
                'Tacoma' => 'Tacoma',
                'Vancouver' => 'Vancouver',
                'Bellevue' => 'Bellevue',
                'Kent' => 'Kent',
                'Everett' => 'Everett',
                'Renton' => 'Renton',
                'Yakima' => 'Yakima',
                'Federal Way' => 'Federal Way',
                'Spokane Valley' => 'Spokane Valley',
                'Bellingham' => 'Bellingham',
                'Kennewick' => 'Kennewick',
                'Auburn' => 'Auburn',
                'Pasco' => 'Pasco'
            ],
            'AZ' => [
                'Phoenix' => 'Phoenix',
                'Tucson' => 'Tucson',
                'Mesa' => 'Mesa',
                'Chandler' => 'Chandler',
                'Scottsdale' => 'Scottsdale',
                'Glendale' => 'Glendale',
                'Gilbert' => 'Gilbert',
                'Tempe' => 'Tempe',
                'Peoria' => 'Peoria',
                'Surprise' => 'Surprise',
                'Yuma' => 'Yuma',
                'Avondale' => 'Avondale',
                'Goodyear' => 'Goodyear',
                'Flagstaff' => 'Flagstaff',
                'Buckeye' => 'Buckeye'
            ]
        ];

        return $cities[$stateCode] ?? [];
    }
}
